version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123?
      POSTGRES_DB: hiking_db
  hiking-api:
    container_name: hiking-app
    image: openjdk:8
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    working_dir: /var/www/html
    command: bash -c "java -jar -Dspring.profiles.active=docker build/libs/hiking-app.jar"
